### ISSUE TITLE
E3 - Front-End

### ISSUE THREAD

**Issue by gabifranklin** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t7-grupopuconstruir#1]
- [x] Login @Rafael-Csza 
- [x] Projetos @gabifranklin 
- [ ] Materiais @CamylaSoares 
- [ ] Serviços  @GabrielC0ut 
- [x] Orçamentos @willamsandradelima 
- [x] Perfil  @Rafael-Csza

**Comment by willamsandradelima** [comment]
Aconteceram alterações de delegação na etapa 4
